name: luxpay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Add flutter spin kit
  flutter_spinkit: ^5.0.0
  # Add toast lib
  fluttertoast: ^8.0.8

  intl: ^0.17.0
  #Carousel
  carousel_slider: ^4.0.0
  #for bio auth
  local_auth: ^2.1.2
  get_it: ^7.1.3
  #Add shared_preferences
  shared_preferences: ^2.0.6
  #Icons
  flutter_iconly: ^1.0.2
  url_launcher: ^6.0.20
  device_info_plus: ^4.0.0
  dio: ^4.0.4
  flutter_riverpod: ^1.0.3
  iconly: ^1.0.1
  flutterwave: ^1.0.1
  intl_phone_field: ^3.1.0
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  flutter_share: ^2.0.0
  flutter_secure_storage: ^5.0.2
  pin_code_fields: ^7.4.0
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.2
  flutter_local_notifications: ^9.1.1
  sqflite: ^2.0.2
  path_provider: ^2.0.2
  dio_http_cache: ^0.3.0
  
  expandable:
  pretty_dio_logger: ^1.1.1
  toggle_switch: ^2.0.1
  webview_flutter: ^2.0.12
 



  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"
  remove_alpha_ios: true

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/btransfer.png
    - assets/ptransfer.png
    - assets/itransfer.png
    - assets/wallet.png
    - assets/coolicon.png
    - assets/facebook.png
    - assets/ig.png
    - assets/sharered.png
    - assets/tweeter.png
    - assets/star.png
    - assets/star.png
    - assets/coins.png
    - assets/package.png
    - assets/cservice.png
    - assets/transactionwithdraw.png
    - assets/transactionpay.png
    - assets/location.png
    - assets/unselect_radio.png
    - assets/fprint_blue.png
    - assets/selected_radio.png
    - assets/exclamation.png
    - assets/construction.png
    - assets/nigeria.png
    - assets/Basic.png
    - assets/Standard.png
    - assets/Premium.png
    - assets/lp.png
    - assets/moreToLife.png
    - assets/fprint.png
    - assets/vault-rafiki.png
    - assets/payment-Information-rafiki.png
    - assets/analytics-rafiki.png
    - assets/bag3.png
    - assets/fund-tag.png
    - assets/transfer.png
    - assets/lp2.png
    - assets/withdraw.png
    - assets/request.png
    - assets/profits.png
    - assets/piggy.png
    - assets/epic.png
    - assets/raise-funds1.png
    - assets/share.png
    - assets/gift.png
    - assets/signup-raise-funds.png
    - assets/play_store_512.png
    - assets/money-profit.png
    - assets/rules-question.png
    - assets/profits/share-link-with-friends.png
    - assets/profits/invitee-accept.png
    - assets/profits/completes-taks.png
    - assets/profits/token-1.png
    - assets/rechargeBills/airtime/mtn.png
    - assets/rechargeBills/airtime/9mobile.png
    - assets/rechargeBills/airtime/glo.png
    - assets/rechargeBills/airtime/airtel.png
    - assets/rechargeBills/airtime/user-id-card.png
    - assets/rechargeBills/airtime/points-money.png
    - assets/paymentMethod/card.png
    - assets/paymentMethod/bank.png
    - assets/paymentMethod/hash.png
    - assets/paymentMethod/mastercard-logo.png
    - assets/paymentMethod/copy.png
    - assets/paymentMethod/bankLogos/access.png
    - assets/paymentMethod/bankLogos/eco-bank.png
    - assets/paymentMethod/bankLogos/first-bank.png
    - assets/paymentMethod/bankLogos/gtb.png
    - assets/paymentMethod/bankLogos/hb.png
    - assets/paymentMethod/bankLogos/uba.png
    - assets/paymentMethod/bankLogos/union.png
    - assets/paymentMethod/bankLogos/wema.png
    - assets/paymentMethod/bankLogos/zenith.png
    - assets/paymentMethod/bankLogos/fcmb.png
    - assets/paymentMethod/bankLogos/stanbic.png
    - assets/paymentMethod/bankLogos/fidelity.png
    - assets/paymentMethod/bankWallpaper/uba-wallpaper-logo.png
    - assets/homeIcons/ad.png
    - assets/homeIcons/betting.png
    - assets/homeIcons/data.png
    - assets/homeIcons/edu.png
    - assets/homeIcons/event.png
    - assets/homeIcons/internet.png
    - assets/homeIcons/transport.png
    - assets/homeIcons/water.png
    - assets/homeIcons/electricity.png
    - assets/homeIcons/airtime.png
    - assets/homeIcons/tv.png
    - assets/successIcon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
        - asset: fonts/Mulish-Italic.ttf
          style: italic
        - asset: fonts/Mulish-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
